### PR TITLE
Refactor package

### PR DESCRIPTION
**Pull request by campagnola**
- Standard python package structure with setup.py, parallax root code folder
- Relative imports within package
- Test code moved to scripts outside package
- Fixed all `import *` instances
- Some cleanup for lib and helper (more needed)
- PEP8-compliant file and variable naming
- Add startup script
- Add license file (presumed AISL)

### CODE REVIEW

**Comment by campagnola** [comment]
Should not be merged until #5 is complete.
Probably easiest to review by looking at diffs one commit at a time.

**Comment by chronopoulos** [comment]
> Should not be merged until #5 is complete.

Do you mean #6 ?

**Comment by campagnola** [comment]
Thanks; #6 is correct

**Comment by chronopoulos** [comment]
Thanks Luke! I pushed some changes on top of this branch:

- reverted the license to MIT (per AIND open science guidelines)
- fixed merge conflicts with master
- fixed some bugs introduced by snake case; mostly these were due to Qt widget methods no longer being overridden (e.g. key_press_event())
- removed some unused functions from lib and helper

Let me know what you think!

**Comment by campagnola** [comment]
Everything looks good to me!

**Pull request merged**
